# netlify.toml  (repo root)
[build]
  command = "npm run build"
  publish = "_site"

[[headers]]
for = "/images/*.webm"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*.mp4"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"


