[build]
  command = "npm run production"
  publish = "dist"

[[headers]]
for = "/images/*.webm"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*.mp4"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
